services:
  quizz-bot:
    image: xorus/quizbot-gauche:dev
    build: .
    volumes:
      - "./data:/usr/src/app/data:rw"
    environment:
      - TOKEN=${TOKEN}
      - DB_PATH=/usr/src/app/data/db.db

